string=  "ALNCXHCAYYUIONMDDHXCBFGCJZXBVCFYDGCCZCVHHGJJKLOUYFHCMZAKIUEYTYFDGCXNBZMALSIEUYDHGCX"
print(string.casefold())

 
# by using def function............

def sample(string):
	print(string.casefold())
sample( "ALNCXHCAYYUIONMDDHXCBFGCJZXBVCFYDGCCZCVHHGJJKLOUYFHCMZAKIUEYTYFDGCXNBZMALSIEUYDHGCX")